In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
features = pd.read_csv("C:/Users/TFG155/Desktop/인공지능개론/AI-class-main/titanic.csv", index_col = 0)

In [3]:
features

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
features['Sex'] = le.fit_transform(features['Sex'])

In [10]:
data = features
data = data.drop(columns=['Name', 'Ticket', 'Cabin', 'Embarked'], axis=1)
data = data.dropna(axis=0)
data

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
PassengerId                                                    
1                   0       3    1  22.0      1      0   7.2500
2                   1       1    0  38.0      1      0  71.2833
3                   1       3    0  26.0      0      0   7.9250
4                   1       1    0  35.0      1      0  53.1000
5                   0       3    1  35.0      0      0   8.0500
...               ...     ...  ...   ...    ...    ...      ...
886                 0       3    0  39.0      0      5  29.1250
887                 0       2    1  27.0      0      0  13.0000
888                 1       1    0  19.0      0      0  30.0000
890                 1       1    1  26.0      0      0  30.0000
891                 0       3    1  32.0      0      0   7.7500

[714 rows x 7 columns]

In [21]:
X = data.iloc[:,1:7].values
y = data.iloc[:,0].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [22]:
X

array([[ 3.    ,  1.    , 22.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  0.    , 38.    ,  1.    ,  0.    , 71.2833],
       [ 3.    ,  0.    , 26.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 1.    ,  0.    , 19.    ,  0.    ,  0.    , 30.    ],
       [ 1.    ,  1.    , 26.    ,  0.    ,  0.    , 30.    ],
       [ 3.    ,  1.    , 32.    ,  0.    ,  0.    ,  7.75  ]])

In [23]:
Y

array([[1, 0],
       [0, 1],
       [0, 1],
       ...,
       [0, 1],
       [0, 1],
       [1, 0]], dtype=uint8)

In [26]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(100,input_shape=(6,),activation='relu'))
model.add(Dense(80,activation='relu'))
model.add(Dense(60,activation='relu'))
model.add(Dense(2,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 100)               700       
                                                                 
 dense_13 (Dense)            (None, 80)                8080      
                                                                 
 dense_14 (Dense)            (None, 60)                4860      
                                                                 
 dense_15 (Dense)            (None, 2)                 122       
                                                                 
Total params: 13,762
Trainable params: 13,762
Non-trainable params: 0
_________________________________________________________________


In [27]:
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
18/18 [==============================] - 1s 16ms/step - loss: 3.0077 - accuracy: 0.5622 - val_loss: 0.6567 - val_accuracy: 0.6853
Epoch 2/100
18/18 [==============================] - 0s 5ms/step - loss: 0.6351 - accuracy: 0.6848 - val_loss: 0.6670 - val_accuracy: 0.6503
Epoch 3/100
18/18 [==============================] - 0s 5ms/step - loss: 0.5874 - accuracy: 0.6918 - val_loss: 0.6132 - val_accuracy: 0.6503
Epoch 4/100
18/18 [==============================] - 0s 9ms/step - loss: 0.5745 - accuracy: 0.6918 - val_loss: 0.6060 - val_accuracy: 0.6573
Epoch 5/100
18/18 [==============================] - 0s 9ms/step - loss: 0.5559 - accuracy: 0.7040 - val_loss: 0.5654 - val_accuracy: 0.7343
Epoch 6/100
18/18 [==============================] - 0s 10ms/step - loss: 0.5636 - accuracy: 0.6900 - val_loss: 0.5490 - val_accuracy: 0.7552
Epoch 7/100
18/18 [==============================] - 0s 9ms/step - loss: 0.5376 - accuracy: 0.7531 - val_loss: 0.6248 - val_accuracy: 0.5874
Epoch 8/100

In [28]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.80      0.94      0.86        79
           1       0.90      0.70      0.79        64

    accuracy                           0.83       143
   macro avg       0.85      0.82      0.82       143
weighted avg       0.84      0.83      0.83       143

[[74  5]
 [19 45]]
