In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

features = pd.read_csv("C:/Users/TFG155/Desktop/인공지능개론/데이터/diabetes.csv",index_col = None, header=0)
features

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [2]:
X = features.iloc[:,0:8].values
y = features.iloc[:,8].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [3]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [4]:
Y

array([[0, 1],
       [1, 0],
       [0, 1],
       ...,
       [1, 0],
       [0, 1],
       [1, 0]], dtype=uint8)

In [5]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(50,input_shape=(8,),activation='relu'))
model.add(Dense(40,activation='relu'))
model.add(Dense(30,activation='relu'))
model.add(Dense(2,activation='softmax'))

model.compile(Adam(lr=0.04),'binary_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                450       
                                                                 
 dense_1 (Dense)             (None, 40)                2040      
                                                                 
 dense_2 (Dense)             (None, 30)                1230      
                                                                 
 dense_3 (Dense)             (None, 2)                 62        
                                                                 
Total params: 3,782
Trainable params: 3,782
Non-trainable params: 0
_________________________________________________________________


c:\Users\TFG155\anaconda3\lib\site-packages\keras\optimizers\legacy\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [6]:
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
20/20 [==============================] - 1s 14ms/step - loss: 6.0867 - accuracy: 0.5798 - val_loss: 0.6470 - val_accuracy: 0.6948
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.6599 - accuracy: 0.6368 - val_loss: 0.6210 - val_accuracy: 0.6948
Epoch 3/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6543 - accuracy: 0.6401 - val_loss: 0.6234 - val_accuracy: 0.6948
Epoch 4/100
20/20 [==============================] - 0s 7ms/step - loss: 0.6532 - accuracy: 0.6401 - val_loss: 0.6226 - val_accuracy: 0.6948
Epoch 5/100
20/20 [==============================] - 0s 10ms/step - loss: 0.6516 - accuracy: 0.6401 - val_loss: 0.6298 - val_accuracy: 0.6948
Epoch 6/100
20/20 [==============================] - 0s 9ms/step - loss: 0.6480 - accuracy: 0.6384 - val_loss: 0.6094 - val_accuracy: 0.6948
Epoch 7/100
20/20 [==============================] - 0s 7ms/step - loss: 0.6469 - accuracy: 0.6482 - val_loss: 0.5968 - val_accuracy: 0.6948
Epoch 8/100

In [7]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.80      0.92      0.86       107
           1       0.72      0.49      0.58        47

    accuracy                           0.79       154
   macro avg       0.76      0.70      0.72       154
weighted avg       0.78      0.79      0.77       154

[[98  9]
 [24 23]]
