In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt
import seaborn as sns

dataset = datasets.load_linnerud()
df = pd.DataFrame(dataset.data, columns = dataset.feature_names)
df

Chins  Situps  Jumps
0     5.0   162.0   60.0
1     2.0   110.0   60.0
2    12.0   101.0  101.0
3    12.0   105.0   37.0
4    13.0   155.0   58.0
5     4.0   101.0   42.0
6     8.0   101.0   38.0
7     6.0   125.0   40.0
8    15.0   200.0   40.0
9    17.0   251.0  250.0
10   17.0   120.0   38.0
11   13.0   210.0  115.0
12   14.0   215.0  105.0
13    1.0    50.0   50.0
14    6.0    70.0   31.0
15   12.0   210.0  120.0
16    4.0    60.0   25.0
17   11.0   230.0   80.0
18   15.0   225.0   73.0
19    2.0   110.0   43.0

In [2]:
print(dataset.keys())

dict_keys(['data', 'feature_names', 'target', 'target_names', 'frame', 'DESCR', 'data_filename', 'target_filename', 'data_module'])


In [3]:
df.columns

Index(['Chins', 'Situps', 'Jumps'], dtype='object')

In [4]:
df.shape

(20, 3)

In [5]:
df_target = dataset.target
df_target

array([[191.,  36.,  50.],
       [189.,  37.,  52.],
       [193.,  38.,  58.],
       [162.,  35.,  62.],
       [189.,  35.,  46.],
       [182.,  36.,  56.],
       [211.,  38.,  56.],
       [167.,  34.,  60.],
       [176.,  31.,  74.],
       [154.,  33.,  56.],
       [169.,  34.,  50.],
       [166.,  33.,  52.],
       [154.,  34.,  64.],
       [247.,  46.,  50.],
       [193.,  36.,  46.],
       [202.,  37.,  62.],
       [176.,  37.,  54.],
       [157.,  32.,  52.],
       [156.,  33.,  54.],
       [138.,  33.,  68.]])

In [6]:
df['label'] = dataset.target[:,1]

In [7]:
df

Chins  Situps  Jumps  label
0     5.0   162.0   60.0   36.0
1     2.0   110.0   60.0   37.0
2    12.0   101.0  101.0   38.0
3    12.0   105.0   37.0   35.0
4    13.0   155.0   58.0   35.0
5     4.0   101.0   42.0   36.0
6     8.0   101.0   38.0   38.0
7     6.0   125.0   40.0   34.0
8    15.0   200.0   40.0   31.0
9    17.0   251.0  250.0   33.0
10   17.0   120.0   38.0   34.0
11   13.0   210.0  115.0   33.0
12   14.0   215.0  105.0   34.0
13    1.0    50.0   50.0   46.0
14    6.0    70.0   31.0   36.0
15   12.0   210.0  120.0   37.0
16    4.0    60.0   25.0   37.0
17   11.0   230.0   80.0   32.0
18   15.0   225.0   73.0   33.0
19    2.0   110.0   43.0   33.0

In [9]:
X = df.iloc[:,0:3].values
y = df.iloc[:,3].values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0) 

In [10]:
X

array([[  5., 162.,  60.],
       [  2., 110.,  60.],
       [ 12., 101., 101.],
       [ 12., 105.,  37.],
       [ 13., 155.,  58.],
       [  4., 101.,  42.],
       [  8., 101.,  38.],
       [  6., 125.,  40.],
       [ 15., 200.,  40.],
       [ 17., 251., 250.],
       [ 17., 120.,  38.],
       [ 13., 210., 115.],
       [ 14., 215., 105.],
       [  1.,  50.,  50.],
       [  6.,  70.,  31.],
       [ 12., 210., 120.],
       [  4.,  60.,  25.],
       [ 11., 230.,  80.],
       [ 15., 225.,  73.],
       [  2., 110.,  43.]])

In [11]:
y

array([36., 37., 38., 35., 35., 36., 38., 34., 31., 33., 34., 33., 34.,
       46., 36., 37., 37., 32., 33., 33.])

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(100, activation = 'elu', input_shape = (3,)))
model.add(Dense(50, activation = 'elu'))
model.add(Dense(1)) 
model.compile(optimizer = 'rmsprop', loss = 'mae', metrics = ['mae'])

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 100)               400       
                                                                 
 dense_16 (Dense)            (None, 50)                5050      
                                                                 
 dense_17 (Dense)            (None, 1)                 51        
                                                                 
Total params: 5,501
Trainable params: 5,501
Non-trainable params: 0
_________________________________________________________________


In [28]:
N_EPOCHS = 100
history = model.fit(X_train, y_train, epochs = N_EPOCHS, validation_data=(X_test, y_test))

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 25.1852 - mae: 25.1852 - val_loss: 8.6335 - val_mae: 8.6335
Epoch 2/100
1/1 [==============================] - 0s 56ms/step - loss: 15.2600 - mae: 15.2600 - val_loss: 9.4143 - val_mae: 9.4143
Epoch 3/100
1/1 [==============================] - 0s 54ms/step - loss: 14.6307 - mae: 14.6307 - val_loss: 10.4998 - val_mae: 10.4998
Epoch 4/100
1/1 [==============================] - 0s 52ms/step - loss: 14.0028 - mae: 14.0028 - val_loss: 9.0321 - val_mae: 9.0321
Epoch 5/100
1/1 [==============================] - 0s 53ms/step - loss: 13.7346 - mae: 13.7346 - val_loss: 10.3733 - val_mae: 10.3733
Epoch 6/100
1/1 [==============================] - 0s 49ms/step - loss: 12.8383 - mae: 12.8383 - val_loss: 11.4747 - val_mae: 11.4747
Epoch 7/100
1/1 [==============================] - 0s 50ms/step - loss: 12.1584 - mae: 12.1584 - val_loss: 12.4771 - val_mae: 12.4771
Epoch 8/100
1/1 [==============================] - 0s 55ms/step - loss

In [29]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 35ms/step - loss: 6.9520 - mae: 6.9520


[6.952014923095703, 6.952014923095703]